// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOQBfYvjwIHogRja1y9-Pe6X6a_cju7E',
    appId: '1:1035802777130:android:b0da73fc7ad704b26b1553',
    messagingSenderId: '1035802777130',
    projectId: 'reserve-51ec8',
    databaseURL: 'https://reserve-51ec8-default-rtdb.firebaseio.com',
    storageBucket: 'reserve-51ec8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJp27CLzpJVO1znx0Che_GfQyZMQ-qnE',
    appId: '1:1035802777130:ios:1c54b4188ed3cd996b1553',
    messagingSenderId: '1035802777130',
    projectId: 'reserve-51ec8',
    databaseURL: 'https://reserve-51ec8-default-rtdb.firebaseio.com',
    storageBucket: 'reserve-51ec8.appspot.com',
    iosClientId: '1035802777130-2b18o8t2eji2hi7hjin9sm1f3bipe83k.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
